FROM node:lts as build
RUN apt -y update

WORKDIR /usr/app

COPY package*.json ./

RUN npm install -g serve

RUN npm install --silent

COPY . .

RUN npm run build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /usr/app/build /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]