name: build-docker-jn-web

on:
  # pull_request:
  #   branches: [dev, main]
  # push:
  #   branches: [dev, main]

  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: echo branch name
        run: echo ${{ steps.extract_branch.outputs.branch }}

      # - name: Build the docker image from production
      #   working-directory: ./
      #   if: ${{ steps.extract_branch.outputs.branch =='main' }}
      #   run: docker build --build-arg REACT_APP_WEB_API=https://jnmoveis.com.br/api --build-arg NODE_ENV=development -f Dockerfile.front -t albuquerquedev/front-orcamento-express:prod .

      # - name: Build the docker image from develop 
      #   working-directory: ./
      #   if: ${{ steps.extract_branch.outputs.branch =='develop' }}
      #   run: docker build --build-arg REACT_APP_WEB_API=https://jnmoveis.com.br/api --build-arg NODE_ENV=development -f Dockerfile.front -t albuquerquedev/front-orcamento-express:dev .
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWD }}

      # - name: Push image to Docker Hub
      #   run: docker push albuquerquedev/front-orcamento-express:prod

      - name: Check out my other private repo
        uses: actions/checkout@main
        with:
          repository: Albuquerquess/jn-infra
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # - name: Terraform Format
      #   id: fmt
      #   run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -backend-config="region=us-east-1" 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: 'terraform'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: list tree AFTER INIT
        run: ls -la

      - name: set dev terraform workspace
        if: ${{ steps.extract_branch.outputs.branch =='develop' }}
        run: terraform workspace select dev || terraform workspace new dev
        env:
          SOURCE_DIR: '.'
          AWS_REGION: 'us-east-1'
          AWS_S3_BUCKET: 'jn-s3-terraform-state'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: set prod terraform workspace
        if: ${{ steps.extract_branch.outputs.branch =='main' }}
        run: terraform workspace select prod || terraform workspace new prod
        env:
          SOURCE_DIR: '.'
          AWS_REGION: 'us-east-1'
          AWS_S3_BUCKET: 'jn-s3-terraform-state'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        


      - name: Terraform validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              TF_ACTION_WORKING_DIR: '.'
              AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # - name: Sync S3
      #   uses: jakejarvis/s3-sync-action@master
      #   env:
      #     SOURCE_DIR: '.'
      #     AWS_REGION: 'us-east-1'
      #     AWS_S3_BUCKET: 'jn-s3-terraform-state'
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
