name: build-docker-jn-web

on:
  pull_request:
    branches: [] # [dev]

  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the docker image
      working-directory: ./

      run: docker build --build-arg REACT_APP_WEB_API=http://jnmoveis.com.br/api --build-arg NODE_ENV=development -f Dockerfile.front -t albuquerquedev/front-orcamento-express:dev .



    - name: list tree
      working-directory: ./
      run: ls -la
