name: build-docker-jn-web

on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the docker image
      working-directory: ./

      run: docker build --build-arg REACT_APP_WEB_API=http://jnmoveis.com.br/api --build-arg NODE_ENV=development -f Dockerfile.front -t albuquerquedev/front-orcamento-express:dev .

    - name: list tree
      working-directory: ./
      run: ls -la && docker image ls

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWD }}

    - name: Push image to Docker Hub
      run: docker push albuquerquedev/front-orcamento-express:prod
