name: build-docker-jn-web

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]

  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the docker image
      working-directory: ./

      run: docker build --build-arg REACT_APP_WEB_API=http://jnmoveis.com.br/api --build-arg NODE_ENV=development -f Dockerfile.front -t albuquerquedev/front-orcamento-express:prod .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWD }}

    - name: Push image to Docker Hub
      run: docker push albuquerquedev/front-orcamento-express:prod

    - name: Setup Terraform
    - uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
