name: build-docker-jn-web-prod

on:
  workflow_dispatch:

  pull_request:
    branches: [main]
    types: [closed]


jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: us-east-1
          role-session-name: GitActionsConfigCredentials

      - name: Add profile credentials to ~/.aws/credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID_PROD }} --profile orcamento-express-prod
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }} --profile orcamento-express-prod

      - name: Build the docker image
        working-directory: ./
        run: docker build --build-arg REACT_APP_WEB_API=https://jnmoveis.com.br/api --build-arg NODE_ENV=prod -f Dockerfile.prod.front -t albuquerquedev/front-orcamento-express:prod .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Push image to Docker Hub
        run: docker push albuquerquedev/front-orcamento-express:prod

  terraform-apply:
    uses: Albuquerquess/jn-infra/.github/workflows/apply.yml@main
    with:
      environment: prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID_PROD}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY_PROD}}
      GH_TOKEN: ${{secrets.GH_TOKEN}}
